### ISSUE TITLE
Problems with U64 numbers

### ISSUE THREAD

**Issue by ALuhning** [graphprotocol/example-subgraph#33]
(In the NEAR implementation) - this line in mapping.ts:

greeting.timestamp = BigInt.fromU64(blockHeader.timestampNanosec);

is causing an error on build - ERROR TS2339: Property 'fromU64' does not exist on type '~lib/arraybuffer/ArrayBufferView'.

**Comment by azf20** [comment]
Hi! What version of graph-ts are you using? This functionality was added in [0.23.1](https://github.com/graphprotocol/graph-ts/releases/tag/v0.23.1)

**Comment by ALuhning** [comment]
Thanks - had just noticed that myself.  Fixed it.
