### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by step21** [graphprotocol/example-subgraph#37]
Assuming matchstick is now the preferred testing method, and as it is also mentioned in the official docks with pointing to this example, could tests be added here?

**Comment by azf20** [comment]
hey @step21 thanks, that is a good thought, will sync with the Matchstick team & get back cc @schmidsi

**Comment by outdoteth** [comment]
+1 on this

**Comment by dimitrovmaksim** [comment]
The link in the docs should lead to this repo https://github.com/LimeChain/demo-subgraph, my mistake
