### ISSUE TITLE
'<' , '>' angular brackets should be removed from CLI commands

### ISSUE THREAD

**Issue by umershaikh123** [graphprotocol/example-subgraph#54]
I was confused why these commands was not working in the powershell or bash terminal in Vs code 
and after I removed the angular brackets the problem was solved. Please change this in your documentation

```
Don't use
graph init --product hosted-service <GITHUB_USER>/<SUBGRAPH NAME>
graph auth --product hosted-service <ACCESS_TOKEN>
graph deploy --product hosted-service <GITHUB_USER>/ <SUBGRAPH NAME>
```

```
use  
graph init --product hosted-service  GITHUB_USER/SUBGRAPH NAME
graph auth --product hosted-service  ACCESS_TOKEN
graph deploy --product hosted-service  GITHUB_USER/SUBGRAPH NAME

```

**Comment by azf20** [comment]
hey @umershaikh123 - sorry for the confusion, which documentation are you referring to specifically?

**Comment by umershaikh123** [comment]
@azf20 I was talking about this documentaion in general when creating subgraph
Documentation : https://thegraph.com/docs/
but most importantly the commands in subgraph dashboard below
![image](https://user-images.githubusercontent.com/42178214/184182620-f0141260-e7fc-425b-b57f-229e56b0d1c8.png)
